version: "3.4"
services:
 vite_docker:
   image: node:18-alpine
   container_name: vite_docker
   entrypoint: /bin/sh
   ports:
     - 8000:8000
   working_dir: /itunes-store
   volumes:
     - type: bind
       source: ./
       target: /itunes-store
   tty: true